# https://taskfile.dev

version: '3'

vars:
  output: "{{.TASKFILE_DIR}}/dist"

tasks:
  build:
    args:
      - output
    cmds:
      - go build -o "{{.output}}/emeral.dll" -buildmode=c-shared main.go
    silent: false

  clean:
    cmds:
      - rm -r "{{.dest}}"
    silent: false

  default:
    cmds:
      - task: build